# Dockerfile for openmetadata_mysql service
FROM docker.getcollate.io/openmetadata/db:1.3.0

# Add custom configuration if needed
COPY ./docker-volume/db-data /var/lib/mysql

# Expose port 3306
EXPOSE 3306

# Command to run the MySQL container
CMD ["--sort_buffer_size=10M"]
