name: Docker Image Build and Azure Container Registry Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: Build and push Docker image to ACR
        id: build
        run: |
         docker build  -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/omd-fundamental:latest . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/omd-fundamental:${{github.sha}}
         docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/omd-fundamental --all-tags
